version: "3.9"

x-IS_PROTOCOL: &IS_PROTOCOL ${IS_PROTOCOL:-http}
x-IS_HOST: &IS_HOST ${IS_HOST:-identity-server}
x-IS_PORT: &IS_PORT ${IS_PORT:-8080}

x-is-envs: &IS_ENVS
  IS_PROTOCOL: *IS_PROTOCOL
  IS_HOST: *IS_HOST
  IS_PORT: *IS_PORT

# logger driver - change this driver to ship all container logs to a different location
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

services:

  identity-server:
    image: "quay.io/keycloak/keycloak:16.1.1"
    container_name: tui-identity-server
    <<: *logging
    environment:
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /tmp/imports/realm-export.json
      KEYCLOAK_USER: tui-admin
      KEYCLOAK_PASSWORD: tui-admin
    volumes:
      - ./volumes/keycloak/realm-export.json:/tmp/imports/realm-export.json:ro
    ports:
      - "8080:8080"
  pilotes-app:
    build: .
    container_name: tui-pilotes-app
    <<: *logging
    environment:
      <<: *IS_ENVS
#      SPRING_PROFILES_ACTIVE: dev-unsecured
    ports:
      - "8081:8081"
  monitoring:
    image: prom/prometheus
    <<: *logging
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    <<: *logging
    volumes:
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./volumes/grafana/dashboards/:/var/lib/grafana/dashboards:ro
    environment:
      GF_SECURITY_ADMIN_USER: 'tui-admin'
      GF_SECURITY_ADMIN_PASSWORD: tui-admin
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/loki.json
    ports:
      - "3000:3000"
    depends_on:
      - monitoring
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
  

networks:
  default:
    name: tui-pilotes
