version: "3.9"

x-IS_PROTOCOL: &IS_PROTOCOL ${IS_PROTOCOL:-http}
x-IS_HOST: &IS_HOST ${IS_HOST:-identity-server}
x-IS_PORT: &IS_PORT ${IS_PORT:-8080}

x-is-envs: &IS_ENVS
  IS_PROTOCOL: *IS_PROTOCOL
  IS_HOST: *IS_HOST
  IS_PORT: *IS_PORT


services:
  proxy: 
    image: nginx:1.21
    volumes:
      - ./volumes/nginx/templates:/etc/nginx/templates:ro
    environment:
      <<: *IS_ENVS
      APP_PORT: 8081
      APP_HOST: pilotes-app
      APP_PROTOCOL: http
      A: 3
    ports:
      - "10000:8080"

  identity-server:
    image: "quay.io/keycloak/keycloak:16.1.1"
    container_name: tui-identity-server
    environment:
      DB_VENDOR: h2
      KEYCLOAK_IMPORT: /tmp/imports/realm-export.json
      KEYCLOAK_USER: tui-admin
      KEYCLOAK_PASSWORD: tui-admin
    volumes:
      - ./volumes/keycloak/realm-export.json:/tmp/imports/realm-export.json:ro
    ports:
      - "8080:8080"
  pilotes-app:
    build: .
    container_name: tui-pilotes-app
    environment:
      <<: *IS_ENVS
    ports:
      - "8081:8081"



networks:
  default:
    name: tui-pilotes
