{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Service",
    "query": "label_values({container_name=~\".+\"}, container_name)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({container_name=~\".+\"}, host)"
   },
   {
    "name": "filter",
    "label": "filter",
    "query": "fatal,error,warn,info,debug,trace"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs $filter",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\", host=~\"$host\"} |~ \"(?i)$filter\" )[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count $filter: of $searchable_pattern ",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\", host=~\"$host\"} |~ \"(?i)$searchable_pattern\" |~ \"(?i)$filter\" )[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{container_name=~\"$container_name\", host=~\"$host\"} |~ \"(?i)$searchable_pattern\" |~ \"(?i)$filter\" "
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time(({container_name=~\"$container_name\", host=~\"$host\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (host)"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per HOST",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(({container_name=~\"$container_name\", host=~\"$host\"} |~ \"(?i)$searchable_pattern\")[30s])) by (host)"
    }
   ]
  }
 ]
}