apiVersion: 1

datasources:
  - name: 'Prometheus'
    type: 'prometheus'
    access: 'proxy'
    org_id: 1
    url: 'http://monitoring:9090'
    is_default: true
    version: 1
    editable: true
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: lokiDataSource
    url: http://loki:3100
    version: 1
    editable: false

