global:
  scrape_interval:     15s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'tui-pilotes scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['pilotes-app:8081']

