server:
  port: ${PORT:8081}
  servlet:
    context-path: /
  error:
    include-message: always

is:
  base-url: ${IS_PROTOCOL:http}://${IS_HOST:localhost}:${IS_PORT:8080}/auth
  realm: ${IS_REALM:tui-pilotes}
  realm-url: ${is.base-url}/realms/${is.realm}
  client-id: tui-gateway
  client-secret: 8JNumTbP0pj8iYoCNgrycb3srA4jBHly

spring:
  data:
    rest:
      basePath: /
      detection-strategy: ANNOTATED
  jpa:
    show-sql: false
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${is.realm-url}/protocol/openid-connect/certs
  main:
    orders:
      allowed_quantity:
      - 5
      - 10
      - 15
      price: "1.33"
      closed_after_seconds: 300
    security:
      white_list:
        - /swagger-ui/**
        - /v3/api-docs/**
        - /purchaserOrders/**
        - /profile/**
springdoc:
  show-login-endpoint: true
  swagger-ui:
    oauth:
      clientId: ${is.client-id}
      clientSecret: ${is.client-secret}


